### ISSUE TITLE
When to support for installing themes?

### ISSUE THREAD

**Issue by Omoinemie** [blastrock/pkgj#144]
The themes tsv has it already, when to support for installing themes?

**Comment by jamesghorn** [comment]
The English to speak your is very good

**Comment by TheRadziu** [comment]
I'd rather wait for proper theme support (via theme promotion [refresh LiveArea]) just like you do with nonpdrm rips (Game promotion) since bgdl method is messy and considered a temporary workaround.

This requires somebody to RE the theme promotion mechanics on Vita and update accordingly vitashell's refresh.c
