### ISSUE TITLE
Download Failure: scePromoterUtilityPromotePkgWithRif failed 0x80010002

### ISSUE THREAD

**Issue by kenzou2009** [blastrock/pkgj#160]
Version of firmware: [3.65]enso
Version of PKGj: [30]

Error
Download Failure: scePromoterUtilityPromotePkgWithRif failed
0x80010002

Hi. i got problem.  After finished download, this error pop.. don't know what to do. if someone got solution, please help me..thanks.. :)

**Comment by KoopaSoup** [comment]
i also get this error after a couple hours of downloading back-ups via pkgj
i can download a bunch of games but then i get this error after 15+games 
it seems my sd2vita card gets corrupted out of nowhere during the download phase because after i get this error the first time,
i am no longer able to install any kind of vpk using vitashell
its so weird because everything works perfect for half a day
then i can no longer install anything on sd2vita but i am still able to play the back ups i managed to obtain off of my sd2vita card even though its "corrupted"
currently on my 4th complete factory reset and the SAME thing happens every time

**Comment by blastrock** [comment]
Maybe there is a bug in nonpdrm then. I can't really do anything about this error on my part.
