### ISSUE TITLE
How to play in PSM on 3.68?

### ISSUE THREAD

**Issue by Rameron** [blastrock/pkgj#188]
Version of firmware: 3.68
Version of PKGj: 0.33

How can I refresh LiveArea database for appearing of PSM bubbles if I'm using Sd2Vita as ux0 partition and it's containing these games?

Obtained result: No PSM Bubbles
Expected result: PSM Bubbles

**Comment by baregl** [comment]
Just researched: According to the comments on https://old.reddit.com/r/VitaPiracy/comments/8zv91g/nopsmdrm_and_368/, you need to have it temporarily on the internal (2000)/official(1000) memory card for the refresh process. After that you can remove it. So maybe just try to copy the ux0:psm folder to your internal/official memory card and try it?

**Comment by Rameron** [comment]
@baregl I will try, thank you. I was avoiding this case because I will need to rebuild database for my micro sd again... 128 GB almost filled by games, it will be so long.

**Comment by baregl** [comment]
I'd use the id.dat way since it seems like it doesn't completly remove old entries. Don't know how it is on 3.68

**Comment by nguyenbakhaihoan** [comment]
I have a tip to install PSM games on Vita Hack 3.68, it can help you:

1. Open PKGJ 0.33 or above, install PSM games like you want
2. Open Vitashell, copy all folders inside ux0:/psm to your PC but for folder ux0:/psm/[TITLE ID]/RO/Application, you don't need to copy all folders inside (or files with big size). So that every folder of [TITLE ID] inside psm has a size of 3~4 MB only
3. Press Start in VitaShell, select USB device is memory card.
4. Press Select in VitaShell and connect your Vita with your PC, copy psm folder from your PC to this memory card
5. Rebuild database by powering off your Vita, and then press PS, power + R1 buttons together, and then select Rebuild Database
6. After your Vita reboot, you will see PSM Games icons on the screen. Go to h-encore to install henkaku again. Press a PSM game, your Vita will ask to install PSM runtime (make sure your DNS was set to 212.47.229.76 before). Two downloads will be process, one will be installed immediately, one will be installed once you lauch PSM again.
7. Go to VitaShell, at the partitions screen, press triangle button and refresh LiveArea. Your icons will appear like before

**Comment by windsurfer1122** [comment]
Shouldn't the rebuild of the database (step 5) be enough? I do not see the point of copying files back and forth (Steps 1.4). Sorry, no access to my Vitas right now.

**Comment by nguyenbakhaihoan** [comment]
Yes step 5 is enough because you don't delete anything, just copy psm folder from ux0 to pc and then from pc to memory card.

When you refresh LiveArea all games and homebrews will appear again

**Comment by Masters110** [comment]
Whats the config file to download PSM?
