### ISSUE TITLE
Please bring back "Vita update"

### ISSUE THREAD

**Issue by u4113057** [blastrock/pkgj#230]
Version of firmware: 3.60
Version of PKGj: 0.41

Please bring back "Vita update" i cant manual update with live area. there is no update show for me to update in live area

**Comment by tonyrayo** [comment]
I believe it's enabled by default now (I received an update regarding having an outdated version, which surprised me but I've been using the software for a few days).  I'm also assuming this since there is a flag for disabling update alerting (no_version_check 1) that you can add to the config.txt.  This is just an FYI,  it's fine if you want to request a more verbose option, which apparently used to exist.

**Comment by blastrock** [comment]
I think he is talking about game updates, no_version_check is for pkgj's updates.

It will come back at some time but it will need some work. I can't just bring them back, the previous updates came from nps and were outdated, so for the moment you need to find out why your updates are not working through livearea.

**Comment by tonyrayo** [comment]
Ah okay, that makes more sense.  Keep up the great work; I love having my whole collection on the go (as well as customizable) and that's fully thanks to coders like you.

**Comment by u4113057** [comment]
can you bring update back and hide it . to enable it just specified something in config.txt instead ?

**Comment by tonyrayo** [comment]
> can you bring update back and hide it . to enable it just specified something in config.txt instead ?

According to the developer, NPS isn't current with updates, which is why this was removed for now.  You should be able to update via the individual live area panel.  If you can connect to the PS Store, you should be able to download updates from the live area after clicking the "refresh" button.  If you can't access the PS Store then there are things that can be tried depending on the error.

**Comment by u4113057** [comment]
> I think he is talking about game updates, no_version_check is for pkgj's updates.
> 
> It will come back at some time but it will need some work. I can't just bring them back, the previous updates came from nps and were outdated, so for the moment you need to find out why your updates are not working through livearea.


can you at least show if version in "PSV_UPDATES.tsv" is match with "entries_patch.txt" then show both download update and patch pack otherwise just show only latestest patch pack ?

**Comment by blastrock** [comment]
I won't bring back the old update feature, I prefer working on the new update system to install the latest update which will work with comp packs. Closing this in favor of #239
