### ISSUE TITLE
GPU Crash after the internet down

### ISSUE THREAD

**Issue by yuriko192** [blastrock/pkgj#24]
so recently i was downloading Akibas's Beat from the pkgj but suddenly my internet went down. the pkgj stop the download but later the system seems to show a GPU crash. i restarted the system and it seems okay at first but when i tried to redownload the game, the system crash again after about 5 or so minutes.

**Comment by yuriko192** [comment]
the system that i was using was the fat PS vita (version 100x)

**Comment by edale2** [comment]
Any problem like this I got were fixed by deleting everything but the config file from ux0:pkgi/ (via VitaShell) and redownloading the game (this folder doesn't contain any completed/installed downloads, so you won't break any of the games you already installed).

PKGj doesn't seem to handle interrupted and/or partial downloads well at all.

**Comment by yuriko192** [comment]
Alright, just deleted all the files in pkgj and it seems to work. Thanks for the help

**Comment by J4ShadyON** [comment]
> Alright, just deleted all the files in pkgj and it seems to work. Thanks for the help

Hi there, I am just having the same issue and I'm just wondering did you also deleted the .db files? if not then maybe I should redo the SD2VITA, I think I lost 8GB due to gpu crash while downloading 2 games from pkgj v0.55

**Comment by edale2** [comment]
I'll be honest, it's been like 2 years since I've touched my PSTV. But as I recall, you delete EVERYTHING but the config file from ux0:pkgi/ (via VitaShell) and nothing else, and then you can start up PKGj and start the download of whatever was causing the issue.

So if a .db file is in ux0:pkgi/, then it gets deleted.

You shouldn't need to redo your entire SD card unless you're having other problems besides a game not downloading properly.
