### ISSUE TITLE
Download failure: scePromoterUtilityPromotePkgWithRif failed: 0x80101107

### ISSUE THREAD

**Issue by MrGlebTiK** [blastrock/pkgj#311]
Version of firmware: 3.73
Version of PKGj: 0.51

## Steps to reproduce the issue

- Install a game that is not on your device (Already 2nd app does not install (I assume that is a patch))
- Wait until the app is waiting to be downloaded
- Download patch

Obtained result: Error: "Download failure: scePromoterUtilityPromotePkgWithRif failed: 0x80101107" or from PSVita installation: "CO-9250-6"
Expected result: installation of patch

Id of the game: PCSE01235
Name: Stardew Valley (2.61 +!) [3.67]
Region: USA
Weight: 154.88 MB

**Comment by TheRadziu** [comment]
Does it still happen with latest pkgj (0.52) ? 
0.52 introduced nonpdrm check, since promoter almost always mean nonpdrm plugin missing from user's system. 

Although do you have PSV or PSTV? If you happen to have PSTV, then error is unrelated to pkgj, since antiblacklist is the culprit here, and in that case you should fully uninstall and undo all antiblacklist modifications and install PolceDolce plugin instead. 

Closing until futher information is provided

**Comment by MrGlebTiK** [comment]
It was happening on PSV. I Downloaded nonpdrm, didn't know I didn't have it. Thanks for the support. When I was downloading it, I saw in config.txt that *KERNEL path was using vitashell. Changed the path to nonpdrm file and everything working. Tysm!
