### ISSUE TITLE
can´t get list: HttpError: sceHttpSendRequest failed: 0x80436007

### ISSUE THREAD

**Issue by timakent365** [blastrock/pkgj#312]
Version of firmware: 3.65
Version of PKGj: v0.51

Start PKGj
Error No items! Try to refresh
I press the triangle button to enter the menu
I choose the option "Refresh"
Then the following error message appears: can´t get list: HttpError: sceHttpSendRequest failed: 0x80436007

**Comment by TheRadziu** [comment]
Make sure that:
- pkgj is updated to latest version (0.52)
- `/pkgj/config.txt` has no custom url overrides 
- NoPayStation domain is accessible on the other devices, as for now russian citizens can't access it due to server range being blocked (some anti-homo law, idk)

**Comment by sergioroprado** [comment]
@TheRadziu 
The config.txt path used to be on pkg"i" folder, this changed to pkg"j" on 0.52? 

I already tryed installing the latest iTLS-Enso, and putting the config.txt on both folders mentioned above, but nothing solves the problem.

**Comment by nmr6cymgvrrk** [comment]
> Make sure that:
> 
> * pkgj is updated to latest version (0.52)
> * `/pkgj/config.txt` has no custom url overrides
> * NoPayStation domain is accessible on the other devices, as for now russian citizens can't access it due to server range being blocked (some anti-homo law, idk)

In Russia it's because RosKomPozor have banned 206.189.0.0/16 subnet (65k ip) trying to block Durov's Telegram messanger. Nopaystation.com site where PKGJ acquiring lists is 206.189.26.46

I've set "[luci-app-unlocker](url https://gitlab.com/Nooblord/luci-app-unlocker/blob/master/SETUP.ru.md)" module to my router to baypass that ban thru TOR network.
You may forge any other VPN workaround to get your Vita to nopaystation.com
