### ISSUE TITLE
Version 0.12 still shows as 0.10

### ISSUE THREAD

**Issue by animekai** [blastrock/pkgj#38]
the 0.12 still shows as 0.10, i've download it from vitadb and from here github, but still shows as 0.10

**Comment by blastrock** [comment]
Do you see the new livearea design? Is there 0.12 written there? On Apr 10, 2018 03:57, animekai <notifications@github.com> wrote:the 0.12 still shows as 0.10, i've download it from vitadb and from here github, but still shows as 0.10

**Comment by animekai** [comment]
i made it work, i will post the steps i made:
-uninstall the app
-then i've installed via vhbb, without results, still in 0.10, but the vhbb said it was 0,12.
-uninstalled again.
-then i've redownloaded the pkgj from github, but this time it works and shows correctly 0.12

maybe the solution was uninstalling first the old version or who knows

**Comment by blastrock** [comment]
That's strange. I've never used vitadb or vhbb so I don't really know how they work. Maybe on the next release try to update manually with the github archive first and see if that works.

I never needed to uninstall pkgj from my vita, but since I'm developing on it, I am not in the same case as you.

**Comment by blastrock** [comment]
Closing since I don't think it's a bug in pkgj
