### ISSUE TITLE
PSP Games - Downloading very/very slowly, not unpacking.

### ISSUE THREAD

**Issue by mrdude2478** [blastrock/pkgj#58]
Version of firmware: [3.60]
Version of PKGj: [0.14]

## Steps to reproduce the issue

Downloaded psp games - zuma (+others)

Obtained result: [Very slow downloads, games not installing]
Expected result: [Faster download, games to install]

On checking the download once PKGJ is completed, the game is still in ux0:/pkgi folder.

eboot.pbp + (sce_sys folder/package/head.bin + tail.bin)

ux0:PSP/GAME/ folder exists on Vita already.

**Comment by blastrock** [comment]
Downloading psp games is slower because they have to be decrypted twice: once to extract the .pkg, and once to convert the eboot.pbp to ISO. I couldn't get a game to work in the eboot.pbp format, so I'm forced to do this operation.

About your installation issue, try to create the ux0:PSP/ISO folder manually. I will improve error reporting for that and automate that folder creation if that's the issue.

**Comment by 1jtp8sobiu** [comment]
For your reference.

By using this PSP plugin with adrenaline,
You can run eboot.pbp as it is.
https://github.com/kyleatlast/npdrm_free

However, it may not be smart as it requires plugin installation and setting.

**Comment by blastrock** [comment]
Thanks for the link @1jtp8sobiu . I'll continue the discussion on the matter on #60

**Comment by mrdude2478** [comment]
@blastrock 

You could add this code, and call that, it would check the ISO folder exists - if not it would create it:

const char* pkgi_check_iso_folder(void)
{
    int dfd;
    dfd = sceIoDopen("ux0:pspemu/ISO"); //check this folder exists
  	if(dfd <= 0)
  		{
  		sceIoMkdir("ux0:pspemu/ISO", 006);
  		}
  	sceIoDclose(dfd);
  	return "ux0:pspemu/ISO";
}
