### ISSUE TITLE
[Config request] Make PSP .PBP / ISO mode selectable

### ISSUE THREAD

**Issue by TheRadziu** [blastrock/pkgj#70]
How about making `config.txt` setting to choose if you would like to use `/iso/Game Name.ISO` or `/game/gameid/EBOOT.PBP`

I really dislike the fact now PSP titles depend on external PSP plugin. Also, /u/deathbladeishere on reddit pointed out that 

> EBOOT.PBP files directly from PSN are NOT smaller lots of games are bloated with update files and dummy files and eboot.pbp files are compressed which causes slowdown in lots of games especially GTA games this needs to be reverted for anybody that cares about size/performance....just to put size into perspective GTA vice city stories as an eboot.pbp is around 1500mb and has very bad slowdown and with its dummy file removed as an iso it is around 1050mb with perfect performance

But since you've already codded it and some people requested .PBP, making such config setting would be the best way to go. Remaining question would be what 'mode' would pkgj use if this setting string is not present in user's `config.txt`

**Comment by seanbperiod** [comment]
100% for this

**Comment by stevenstrike** [comment]
Not only that but some games will not work (ex : Splinter Cell and PowerStone Collection) in eboot format.
(These same games have also a problem in ISO format where they need to be started using NP9660 if using Adrenaline Bubbles)

**Comment by blastrock** [comment]
I see your concern. Here are some remarks and questions:

> I really dislike the fact now PSP titles depend on external PSP plugin.

Not sure this argument is receivable but the user already needs to install Adrenaline, so it's just one more dependency.

> GTA vice city stories as an eboot.pbp is around 1500mb and has very bad slowdown and with its dummy file removed as an iso it is around 1050mb with perfect performance

I don't know about performance, but from what I can see, that game is 1.6GB in PBP *and* in ISO format, there is no difference. An ISO, as generated by pkgj (whose code comes from pkg2zip), is just an EBOOT.PBP file, decrypted and decompressed, so it can't be smaller than the PBP file (or I missed something big).

As for performance, does it mean that the official game on a non-CFW vita has the same problems?

> Remaining question would be what 'mode' would pkgj use if this setting string is not present in user's config.txt

If I add that option, the ISO mode is the way to go I think as it is the one that works more out-of-the-box.

I was actually quite happy to remove all that decryption and decompression code from pkgj :(

**Comment by mrdude2478** [comment]
Nooooooo, keep the PBP. It's far faster to download and install.

If people want ISO - they can easily extract the ISO from the PKG with tools that are already available.

**Comment by 1jtp8sobiu** [comment]
I also like eboot.pbp format.
The manual is available and it is actually close to the official launch method.
This also relates to starting PC Engine games.

However, I think that is wonderful if it's selectable.

**Comment by seanbperiod** [comment]
Basically, both options have their pros and cons. So having the option to support both methods would be great. Which one gets enabled by default is the question. We appreciate your work @blastrock !

**Comment by deathbladeishere** [comment]
> Not sure this argument is receivable but the user already needs to install Adrenaline, so it's just one more dependency.  

you mean just one more compatibility issue to add on top?

 

>  I don't know about performance, but from what I can see, that game is 1.6GB in PBP and in ISO format, there is no difference. An ISO, as generated by pkgj (whose code comes from pkg2zip), is just an EBOOT.PBP file, decrypted and decompressed, so it can't be smaller than the PBP file (or I missed something big).

this statement was mostly about your claim of saying they are smaller when really as you already explained they are not as they are filled with lots of useless language files/update files/and dummy files if anything if your going to leave these games compressed like this you might as well just make them cso files now THAT would actually save space and have the exact same performance issues that eboot.pbp files have

> As for performance, does it mean that the official game on a non-CFW vita has the same problems?

yes actually although people who don't really know any better will say its not true compression will effect the performance of the games and you can find evidence of that from a simple google search GTA games being the biggest culprit because of their constant file streaming

> If I add that option, the ISO mode is the way to go I think as it is the one that works more out-of-the-box. I was actually quite happy to remove all that decryption and decompression code from pkgj :(

as already stated if people are wanting smaller files then you might as well give a cso and iso option because as stated csos would be smaller than eboot.pbp with the same performance issue while iso will have vastly superior performance with the downside of more space used

**Comment by blastrock** [comment]
> In case of ISO format, the patch is not applied. (Except using ISO TOOL etc.)

Does that mean that there is no way to update games at all on PSP?

> this statement was mostly about your claim of saying they are smaller when really as you already explained they are not as they are filled with lots of useless language files/update files/and dummy file

I'm not sure I'm following you. EBOOT file are smaller, or at least the same size as ISO files, as ISO files are an uncompressed version of EBOOT. If the EBOOT contains garbage files, the ISO will contain it too.

> you might as well just make them cso files

I don't really want to go with CSO as it implies even more code. From what I can see, a CSO is an ISO compressed with a DEFLATE algorithm, whereas a compressed EBOOT is compressed using something close to LZMA, which is, from what I know, much better than DEFLATE in terms of compression, but much worse in terms of speed. So a CSO is something in-between an ISO and a compressed EBOOT in terms of compression and reading speed.

In the case of GTA, I just noticed that the EBOOT is not compressed at all, that's why they are the same size.

> compression will effect the performance of the games

So, in the case of GTA, it's not compression, just decryption.

---

Anyway, seeing you guys' reactions here, I understand that you need this. I will make an option for it. In the meantime, I suggest staying on the previous version.

**Comment by deathbladeishere** [comment]
> I don't really want to go with CSO as it implies even more code. From what I can see, a CSO is an ISO compressed with a DEFLATE algorithm, whereas a compressed EBOOT is compressed using something close to LZMA, which is, from what I know, much better than DEFLATE in terms of compression, but much worse in terms of speed. So a CSO is something in-between an ISO and a compressed EBOOT in terms of compression and reading speed.

wrong for example the 560mb liberty city stories cso runs exactly the same as the 1100mb eboot.pbp

> In the case of GTA, I just noticed that the EBOOT is not compressed at all, that's why they are the same size.

it is compressed all eboot.pbp files are compressed some not compressed as well as others but its still a compressed file regardless

> So, in the case of GTA, it's not compression, just decryption.

wrong you can create a iso file and see it running perfectly and then turn that same iso in a cso and see it run exactly the same as the eboot.pbp

**Comment by blastrock** [comment]
> it is compressed all eboot.pbp files are compressed some not compressed as well as others but its still a compressed file regardless

Ok, I was a bit wrong, maybe all (or most) of eboot files are at least a bit compressed, but this is not a matter of files being better compressed than others in an algorithmic sense. That GTA game is an eboot file composed of 1420 LZRC compressed blocks and 50338 uncompressed blocks of 32KB. This is why the CSO file is smaller. I don't know how much LZRC differs from LZMA, but even the worse LZMA setting outperform the compression ratio of the best DEFLATE setting. Some comparisons on page 4 [here](https://cran.r-project.org/web/packages/brotli/vignettes/brotli-2015-09-22.pdf). What I meant is that as CSO is in-between a *compressed* eboot and an ISO.

> wrong you can create a iso file and see it running perfectly and then turn that same iso in a cso and see it run exactly the same as the eboot.pbp

Yes, it may run the same, but not for the same reasons. In the case of the EBOOT, it is slow because of encryption, in the case of the CSO, because of compression, and the ISO is not encrypted nor compressed.

**Comment by deathbladeishere** [comment]
> Ok, I was a bit wrong, maybe all (or most) of eboot files are at least a bit compressed, but this is not a matter of files being better compressed than others in an algorithmic sense. That GTA game is an eboot file composed of 1420 LZRC compressed blocks and 50338 uncompressed blocks of 32KB. This is why the CSO file is smaller. I don't know how much LZRC differs from LZMA, but even the worse LZMA setting outperform the compression ratio of the best DEFLATE setting. Some comparisons on page 4 here. What I meant is that as CSO is in-between a compressed eboot and an ISO.

they are ALL compressed some files just can't compress as well as others same as any other compression archive and  this game is simply an example regardless all games will end up saving space in cso format I've done MANY tests in the past to know that. only some can't compress very well due to them being packaged tightly already inside the iso such as ff7 crisis core

> Yes, it may run the same, but not for the same reasons. In the case of the EBOOT, it is slow because of encryption, in the case of the CSO, because of compression, and the ISO is not encrypted nor compressed. 

idk where you are trying to pull this encryption thing from but its not true at all unless your going to try and tell me it effects my purchased versions of vice city stories and liberty city stories as well considering they have the same exact slowdown...accept it or not EBOOT and CSO are both effected by the same thing compression

**Comment by blastrock** [comment]
Well, I am pulling all this from the code of pkgj and pkg2zip. What I understood of the conversion process from EBOOT to ISO is that there is first an AES decryption, and then, on some blocks, a LZRC decompression. If GTA is slow, it is very unlikely to me that it comes from the few compressed blocks.

But anyway, we are getting off topic here...

**Comment by deathbladeishere** [comment]
thats to say that every game that runs slow as a eboot.pbp is due to encryption which is just not true. compression puts more work on the hardware as it has to decompress it on the fly. regardless of how much of it is compressed the whole game is still in a compressed format

**Comment by mrdude2478** [comment]
@blastrock 

Just ignore that guy, he can't be reasoned with and he is argumentative. The new code you wrote is a BIG improvement, especially on downloading/extraction times. I for one like the eboot.pbp format - and so do Sony or they wouldn't use it in their games. The vita is more that capable of decompressing this on the fly. As for game loading times - I see very little difference between ISO and PBP, but if I did I could easily convert to ISO on a PC as all the tools are available. The vita takes too long to do this conversion, so it's far better to stick to PBP.

Thanks.

**Comment by seanbperiod** [comment]
Thanks @blastrock !

**Comment by deathbladeishere** [comment]
>Just ignore that guy, he can't be reasoned with and he is argumentative.

>says the guy who freaked the fuck out when I gave facts in my original posts its not my fault if you cant see the difference but that does not change the fact that it causes a performance hit

>and so do Sony or they wouldn't use it in their games. 

or they would for encryption purposes with the extra benefit compression
