### ISSUE TITLE
v0.21 downloading games issue  

### ISSUE THREAD

**Issue by KingOfFakes** [blastrock/pkgj#86]
Version of firmware: [3:60]
 Version of PKGj: [v0.21]

First time using PKGi on my ps vita. I tried downloading Child Of Light 3 times. 
I just selected the game and ones it gets to 99% download it stops for a few seconds and i get error (error (download failure :scepromoterutilitypromotepkgwithrif failed: 0x80870004). 
I read other posts about this occurring to games over 2Gb. So i decided to try a smaller sized game which was  Baseball Riot, and still got the same error message. 
The game ids are PCSE00834 and PCSE00480.  

I had not previously used an older version of PKGI, so it was an clean install.
I downloaded the files: pkgj.vpk, Source code (zip) and config.txt

The config.txt file contains: 
url_games http://nopaystation.com/tsv/PSV_GAMES.tsv
url_updates http://nopaystation.com/tsv/PSV_UPDATES.tsv
url_dlcs http://nopaystation.com/tsv/PSV_DLCS.tsv
url_psx_games http://nopaystation.com/tsv/PSX_GAMES.tsv
url_psp_games http://nopaystation.com/tsv/PSP_GAMES.tsv
sort name
order asc
filter JPN,USA

**Comment by blastrock** [comment]
Do you have nonpdrm?

**Comment by KingOfFakes** [comment]
Yes i do. I deleted PKGI from the ps vita and installed it again, but still gives me the same error.

**Comment by SunsetThrone** [comment]
Same issue downloading stuck at 99%

**Comment by Q113P** [comment]
I have a similar issue/problem and would like help with it. I got pkgj v. 021 to load the list but I can't download. It keeps giving me an error "download failure : pkgj integrity failed, try downloading again. I have nonpdrm set up and I don't know what the problem is. I also have another issue that happened when I exited out/closed the app (I was about to swipe it to close it and I did something stupid - and reinserted my game card. It automatically opened maidump and did something to the cartridge and now it doesn't work at all and I think it earasd it). I tried asking for help somewhere else but it's going on 3 days without any help and I would love to use my Vita again

**Comment by blastrock** [comment]
Seem very similar to #74 though. If you think this comes from pkgj, you can try installing your game manually with NPS browser and refreshing livearea with vitashell, you will probably have the same issue.@Q113P For the package integrity failure, it seems like an internet connectivity issue, maybe a proxy or your ISP doing things... I can't help with your cartridge issue.

**Comment by Q113P** [comment]
Oh OK, yeah I'll have to figure out the card issue myself.
Anyways, I installed pkgj and followed the tutorial correctly so I don't know why I would get an internet connection issue or those thngs you mentioned. I only ever used the connection to load hakuo 3.60 since I never did the permanent cfw. I don't know what to do. Is there something in the menu, settings or something?

**Comment by blastrock** [comment]
There's nothing to configure about that. What you can try is to download the game file (the .PKG file) from the web browser on the Vita, copy the file to a computer and do a sha256sum there (there should be many tools for any OS out there to do it, just Google it). Then compare the sha256 with the one that's in the TSV file. If it's different it would confirm that there is something wrong with your vita.Also, I never used pkgj without permanent cfw, so I can't be sure it works like that.On Jun 3, 2018 04:48, Q113P <notifications@github.com> wrote:Oh OK, yeah I'll have to figure out the card issue myself.
Anyways, I installed pkgj and followed the tutorial correctly so I don't know why I would get an internet connection issue or those thngs you mentioned. I only ever used the connection to load hakuo 3.60 since I never did the permanent cfw. I don't know what to do. Is there something in the menu, settings or something?

**Comment by Q113P** [comment]
OK well I did use the No Pay Station app for my PC and it is the same.
OK so I managed to get a game but when I go and play it it says, error C1-6703-6

**Comment by TheRadziu** [comment]
@Q113P seems like you have 3.68 exploit on hands, why don't you share it with rest of the community? /s

**Comment by Q113P** [comment]
@TheRadziu what? All I did was download it and loaded it wanting to play it. I did nothing special. I don't know what the problem is. I spoofed the fw on, 3.65, 3.67 and 3.68  and same problem.

**Comment by TheRadziu** [comment]
@Q113P because its 3.67 game. If your firmware is 3.65 or 3.60 you can run those. We do not add **(3.61+!)[3.67]** to the names just for the looks.

**Comment by edale2** [comment]
Spoofing is for the PSN Network, nothing else, and I don't believe spoofing works properly for 3.60 anymore.

If you want to play any game that requires a firmware 3.61-3.65, you'll need to update to Enso 3.65 yourself. For games requiring 3.67, you'll need to wait until the end of the year for the 3.67 CFW to be released (I'm not aware if an exploit for 3.68 has been found yet, but 3.67 is already exploited and just waiting for the end of the Vita's lifecycle to be released).

Alternately, I believe some people have been converting some of the 3.65 games to work on 3.6 firmware (I _think_ using MaiDump), you'll have to find those yourself though.



For the cartridge problem... Try the cartridge in a different Vita (worst-case, most used game stores will let you test a cartridge on one of their used systems) and see if it works. If it does, then the problem is with your Vita.
If this is the case, the first step of the Enso 3.65 upgrade instructions basically has you returning your Vita to stock condition, you can follow the instructions up to that point, and then instead of upgrading, remod your vita with Henkaku/Enso 3.6.
If the problem was caused by MaiDump, then uninstalling/reinstalling MaiDump may fix it.

**Comment by inkael** [comment]
Well I had this problem today and I erased the config.txt and created it with vitashell, wrote the same things and worked well.

**Comment by blastrock** [comment]
I guess it works now
